### PR TITLE
Documentation of changes up to this point

### LINKED ISSUE #45: Document code merged already
Add support for Doxygen and add Doxygen comments to code merged already via previous pull requests in support of User Story #44.

Completion Criteria: Documentation comments exist for code previously merged since forking and these comments build into proper Doxygen documentation.

Due: Tuesday, April 6

### PR DESCRIPTION
**Pull request by jcgoble3**
Added Doxygen support and documentation up to this point for our changes as part of Task #45.

Of note: Doxygen does not work very well with Python. Its support for using Python docstrings is poor, hence the forced usage of regular comment syntax for documentation, which is considered extremely poor form for Python code (all in-code documentation *should* be in docstrings). Sphinx would have been better in this regard as it was designed *for* Python and designed to use docstrings, but at this point I'd rather just burn through this semester without rethinking it as the documentation herein will be one of the first things I delete after the semester is over anyway regardless of tool.

Some syntax notes:
- The usage of two hash marks (`##`) is the signal to Doxygen that this comment is documentation.
- `@story{X}` (or `\story{X}`, use whichever one you prefer) is an alias I created to automatically link to a user story here on GitHub.

### CODE REVIEW

**Comment by sethsarchet** [comment]
Was just taking a look through all the things you changed, and it looks really good. I feel like you explained what and why the code was doing what it was doing very well. Nice job Jonathan 👏🏻

**Comment by jluckenbill** [comment]
Comment additions look good. They are clear, well explained and do a good job of explaining the why of each commented item. Looks good to merge.

**Review by jluckenbill — APPROVED** [review]
Comment additions look good. They are clear, well explained and do a good job of explaining the why of each commented item. Looks good to merge.

**Review by dward118 — COMMENTED** [review]
The commenting following doxygen is implemented efficiently with in the code.

**Pull request merged**
